Ensure that under Linux GLIBC option parsing is done without allowing option/argument permutations to avoid accidentally picking up and complaining about unknown options.
Required standard POSIX getopt(3) behavior:
  $ rpm --define '%foo() <%*>' --eval '%{foo bar %(echo -n "quux") baz}'
  <bar quux baz>

Unexpected non-standard Linux GLIBC getopt(3) behavior:
  $ rpm --define '%foo() <%*>' --eval '%{foo bar %(echo -n "quux") baz}'
  foo: invalid option -- n
  error: Unknown option ? in foo()
  <%*>

Fixed standard POSIX getopt(3) behavior also under Linux GLIBC:
  $ POSIXLY_CORRECT=1 rpm --define '%foo() <%*>' --eval '%{foo bar %(echo -n "quux") baz}'
  <bar quux baz>