work around "byte" type conflict, between RPM and BeeCrypt
.../beecrypt/api.h:66: error: redefinition of typedef 'byte'
./rpmpgp.h:27: error: previous declaration of 'byte' was here