RPM really has to use the POPT_CONTEXT_POSIXMEHARDER flag to (again) correctly parse macro arguments *without* option/argument permutations now that we are using POPT instead of getopt(3)!
Broken behavior without POPT_CONTEXT_POSIXMEHARDER:
  $ rpm --define '%foo() <%*>' --eval '%{foo bar %(echo -n "quux") baz}'
  error: Unknown option in macro foo(): -n: unknown option
  <%*>

Fixed behavior with POPT_CONTEXT_POSIXMEHARDER:
  $ rpm --define '%foo() <%*>' --eval '%{foo bar %(echo -n "quux") baz}'
  <bar quux baz>