Resolve the following declaration conflict (occured under Sun Solaris):
| rpmio.c:79: error: static declaration of 'inet_aton' follows non-static declaration
| /usr/include/arpa/inet.h:52: error: previous declaration of 'inet_aton' was here